### ISSUE TITLE
Add notes, thoughts, musings  unrelated to pdf

### ISSUE THREAD

**Issue by TheNomad11** [mkucej/i-librarian#127]
I librarian is great, I am happy that I found it. It would be even more useful if it would be possible to add thoughts, musings and other notes that are independent of the articles stored in the database. I think about notes that are f.ex. related to a writing project

**Comment by hansduo** [comment]
That is already possible via Notes>Edit. 
Unfortunately these notes are private.
A long standing feature request of mine would be the possibility to allow shared notes.
Discuss(ion) is a nice related feature, but not the same.

update:
Sorry, I misread your post.

2nd update:
But it is already possible - in a way...  Because You can see project related notes compiled for You, if You go to a project and click on "Notes". The Notes are still attached to the articles, but You can group them project-wise.  And they are in fact shared among all accounts that are part of the project. So my request has been (partly) fullfilled.
Anyway I would like a possibility to publicly (i.e. for all logged in users) share notes, for example to explain the flaws or highlights of a publication...

**Comment by hansduo** [comment]
An easy way to have that feature is to create an entry with a dummy PDF. Enter yourself as the Author, title it "My Notes" or sth. like that and go ahead to add Notes as with the real articles.

**Comment by mkucej** [comment]
Thanks for your suggestion.

 > Unfortunately these notes are private.

Notes will be readable by all users, writable by the author in version 5.

**Comment by hansduo** [comment]
Nice!

**Comment by TheNomad11** [comment]
Any news about version 5? Is it still being worked on or is this project dead, @mkucej ?

**Comment by mkucej** [comment]
@TheNomad11 Thanks for asking. It is not dead. In fact we just uploaded a beta to our server for you guys to mess with:
https://i-librarian.net/article.php?id=12
https://i-librarian.net/beta

**Comment by mkucej** [comment]
> I think about notes that are f.ex. related to a writing project.

BTW, project notes are now a thing.
