### ISSUE TITLE
password displayed - manual HTTP proxy configuration:

### ISSUE THREAD

**Issue by tbugfinder** [mkucej/i-librarian#25]
If a manual proxy is configured the password is always visible to super users.
Could you user a password field here?

**Comment by mkucej** [comment]
Hmm. I just learned that IT departments force users to use their "secure" passwords for proxy access. That is bad, because proxy requires the password in unencrypted format, and therefore must be stored in a plain text format at least while a user is signed in I, Librarian. The proxy password management will have to be changed completely. Thanks for reporting this.

**Comment by tbugfinder** [comment]
Hmm, first of all I'd like to see ****** instead of the password itself.
Secondly I also see the option that each user saves proxy authentication credentials within the application however I do not like this either. In our current setup a "generic/shared" proxy user (no other privileges) is configured for I, Librarian.

**Comment by mkucej** [comment]
1. Yes, we will change the input to type "password".
2. Actually, only a super user can set proxy credentials and these are set to all users in the library. The users and guests are not exposed to this setting.

**Comment by mkucej** [comment]
Fixed.
