### ISSUE TITLE
PDF subfolder code?

### ISSUE THREAD

**Issue by dlancia** [mkucej/i-librarian#63]
Hi,

I'm in the process of migrating iLibrarian from a Linux to Windows server.  My Linux install has been active for a long time so it has >25,000 records all at the base of the "library" folder.

New installs of iLibrarian use a "library/pdfs" subfolder with additional subfolders to prevent too many files from ending up in one directory.

Is there a preferred or automated way of upgrading an old monolithic library to a the broken up folder setup or am I going to have to manually move the files and edit the sqlite databases?

Thanks.

**Comment by dlancia** [comment]
Hi,

My initial comments were due to a conflict of versions.  I used an old backup of a library from 3.5 with a clean install of 4.1.  The PDFs did sort themselves out of the library folder.

I think there is still an issue though.  All 25,000+ files ended up in the 01 subfolder.  This is due to the code in functions.php:

// get numbered subfolder where file resides
function get_subfolder($file) {

    $file = substr($file, 0, 5);
    return sprintf("%02d", floor(intval($file) / 100000) + 1);

}

This code will never return anything other than 01 for the subfolder because $file can be at most a 5 digit number and then you divide it by 100000 and floor the remainder.  

This should probably divide by a smaller number (1000 would be a good number per folder especially on Windows) or you could just use the first 2 digits of the file name directly because it is limited to 5 digits in the SQL insert statements.

And a related point, the file name is limited to 9 characters based on the SQL input statement on upload (5 file name + "." + 3 extension).  This means that iLibrarian can only handle a maximum of 99,999 PDFs.  Can you look into increasing this during on of your next releases?

Thanks,
David

**Comment by mkucej** [comment]
> Is there a preferred or automated way of upgrading an old monolithic library to a the broken up folder setup or am I going to have to manually move the files and edit the sqlite databases?

Yes, the upgrade process takes care of moving all PDF files.

> This code will never return anything other than 01

Correct. It has only been added there for future compatibility with Enterprise version of `I, Librarian`, that will be able to handle up to 1 million documents.

> This should probably divide by a smaller number (1000 would be a good number per folder especially on Windows)

Up to 100,000 files is not a big problem on Linux (our target platform). We can consider splitting in groups of 10,000.

>  This means that iLibrarian can only handle a maximum of 99,999 PDFs.

That's correct. It is a hard-coded limit. Because of the way `I, Librarian` is written right now, it is unrealistic to expect good performance with more files than that. We are planning an enterprise version that will be able to handle up to 1 million documents. Your 25,000 documents is still OK, but when you have over 60-80,000, you will see significant slow downs. Unfortunately, `I, Librarian` was not designed with these huge needs in mind.

**Comment by mkucej** [comment]
Changed in 4.4
