### ISSUE TITLE
Required binary executables

### ISSUE THREAD

**Issue by Pigno** [mkucej/i-librarian#64]
After the installation of the package (all in one) on Windows : 

In the Installation details Menu, i have many line in error : 

Pdftotext	PDF full-text search	not working	!!!
Pdfinfo	built-in PDF viewer	not working	!!!
Pdftohtml	PDF search in the built-in PDF viewer	not working	!!!
Ghostscript	icon views, built-in PDF viewer	not working	!!!
Pdfdetach	unpacking PDF-attached files	not working	!!!
Optional binary executables:
Tesseract OCR	optical character recognition	not working	!!!
LibreOffice	office documents import and conversion	not working	!!!

I don't understand why they don't work. The package are in the Bin directory of I,Librarian.

Any idea ?

Thanks a lot !

**Comment by mkucej** [comment]
Could you try to install newer Visual C++ Redistributable Packages?

https://support.microsoft.com/en-us/kb/2977003

**Comment by JMPeryn** [comment]
I have the same problem. I just tryed to install de latest Visual C++ package .. it changed nothing.

**Comment by Pigno** [comment]
Hello, thanks for your answer but it changed nothing too.

**Comment by mkucej** [comment]
There is a regression in _I, Librarian_ 4.x, which causes this bug, if _I, Librarian_ is installed in a folder that contains white space in its name. It will be fixed in the next release. In the meantime, you can uninstall your existing _I, Librarian_, and install again into a new folder, e.g. `c:\i-librarian`. Finally, copy your library folder from `c:\I, Librarian` to `c:\i-librarian`. Just renaming your existing install directory will not fix the issue.

Thank you for reporting this issue, it is much appreciated.

**Comment by Pigno** [comment]
Great ! That's work perfectly ! 
Thanks you !

**Comment by JMPeryn** [comment]
Worked perfectly, thanks

**Comment by mkucej** [comment]
fixed in 4.2

**Comment by ginkr** [comment]
I come across the same problem. I install I, Librarian on a Linux machine (Centos 7). I tried to install all required softwares, such as gs, tesseract-ocr, and etc. Could anyone help me figure out what's wrong here? Thanks.
