### ISSUE TITLE
Standalone desktop version?

### ISSUE THREAD

**Issue by baimafeima** [mkucej/i-librarian#96]
Could you also make **I, Librarian** available as a standalone desktop version (similar to Zotero standalone version, colwiz or Mendeley)? Self-hosting is more complicated and even though you offer a web version, there are lots of people - I believe - who prefer to work with a traditional desktop-based application.

**Comment by mkucej** [comment]
Thank you for your suggestion. A standalone version is not our priority at the moment.

**Comment by baimafeima** [comment]
Thank you for being open to the suggestion.

**Comment by baimafeima** [comment]
Out of curiosity, do you mean it is on the roadmap but not prioritized at the moment or something you are not considering for 2017? I'd be willing to help with testing, set up a patreon page, and otherwise sponsor such a standalone version.

**Comment by mkucej** [comment]
A desktop version is not on the roadmap currently. We are an SaaS company first and foremost. In addition, it is unlikely that there would be any return to such investment to a saturated market. I must stress that we value community involvement. Not only is I, Librarian open-source, but we are doing our best to provide convenient installation packages for Windows and Ubuntu users. We will be happy to host and promote a community effort to maintain an installer for Mac OSX.

**Comment by baimafeima** [comment]
Thank you for your feedback. I understand your hesitation in regards to ROIs. I would be particularly interested in having a desktop standalone version for use under Linux-based operating systems such as Solus, Debian or openSUSE, in short, a better version of Mendeley with options to sync (no forced syncing). Such a version could be entirely community-funded through a Patreon page. 
- How do you evaluate the current codebase to be suitable for such a community effort?
- Would you encourage a community-maintained fork of the current codebase to create a standalone version independent of your offerings? Are there any restrictions that would prevent this?

**Comment by mkucej** [comment]
What are the reasons that you would prefer a desktop version? Is it the native window appearance instead of an Internet browser, easier installation,  syncing to cloud services?

IMO, there are no libraries to create good native PHP apps, and I also think that would be too much work.

If you want easier installers, you are welcome to create better packages, and we will host/promote them on our web site. There is also a Dockerfile project, you can help there:
https://github.com/cgrima/docker_i-librarian

As for syncing, new classes could be added to sync to Amazon, Google, or others to the master branch. Do you want to contribute them?

I, Librarian code is quite discombobulated. It is an old application, started before PHP had any OO concepts. The code is GPLv3-licensed, which enables you to create a fork provided you comply with the license terms.

**Comment by baimafeima** [comment]
> What are the reasons that you would prefer a desktop version? Is it the native window appearance instead of an Internet browser, easier installation, syncing to cloud services?

Apologies for the late reply. These are all good reasons. I really prefer to work offline on my local computer and only use cloud services when I want to sync. A native window appearance is certainly preferred over working with an Internet browser.

**Comment by Zugrik** [comment]
> Thank you for your feedback. I understand your hesitation in regards to ROIs. I would be particularly interested in having a desktop standalone version for use under Linux-based operating systems such as Solus, Debian or openSUSE, in short, a better version of Mendeley with options to sync (no forced syncing). Such a version could be entirely community-funded through a Patreon page.

If you a Linux user, there should be no problems with self-hosting I, Librarian. I have been doing it for more than 5 years and full installation takes a few seconds: apache and all other stuff works great out of box. After that, Web interface seems to me not that different than it would be at Desktop app.

Best.
